spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-notif-service
          uri: lb://user-notif-service
          predicates:
            - Path=/api/auth/**
        - id: user-notif-service-users
          uri: lb://user-notif-service
          predicates:
            - Path=/api/users/**
        - id: user-notif-service-static-files
          uri: lb://user-notif-service
          predicates:
            - Path=/uploads/**
        - id: lamain-service
          uri: lb://lamain-service
          predicates:
            - Path=/api/lamain/**
