spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-notif-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
            - Path=/api/users/**
        - id: lamain-service
          uri: lb://lamain-service
          predicates:
            - Path=/api/lamain/**
