server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sirh_lamain
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        notificationTopic-out-0:
          destination: notifications
  
  # Configuration de Kafka
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: sirh-notification-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # Indique à Spring de faire confiance aux packages pour la désérialisation JSON
        spring.json.trusted.packages: '*'
        # Spécifie la classe cible par défaut pour la désérialisation de la valeur.
        spring.json.value.default.type: com.ngombe.sirh.lamain_service.dto.NotificationEventDto
        # Force le désérialiseur à ignorer l'en-tête de type, évitant ainsi l'erreur de "Class not found".
        spring.json.use.type.headers: false
    # Configuration du producteur Kafka
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
    listener:
      ack-mode: manual
    template:
      default-topic: sirh-notifications

jwt:
  secret: c980bef910d21eed63b5d4ea82c575ce82022fd139c3a183c2a9d163f3f73e5251f80762b718b4b293bcc37ea7163f7f1b3cc9f0101508f845fec8409e18fa3c
  expiration: 86400000
  refresh-token:
    expiration: 604800000

user-notif.service.url: http://user-notif-service:8083
user-notif:
  service:
    url: http://user-notif-service:8083
  base-url: http://localhost:8083

notification:
  kafka:
    topic: sirh-notifications