# Configuration du serveur
server:
  port: 8085

# Configuration de la base de données MySQL avec R2DBC
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/sirh_notification_service
    username: root
    password: ""

  # Configuration de Flyway pour la gestion du schéma
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/sirh_notification_service # Notez le protocole JDBC ici
    user: root
    password: ""
    locations: classpath:db/migration
    baseline-on-migrate: true # Utile pour les bases existantes

  # Configuration de Kafka
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
    listener:
      ack-mode: manual
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
      template:
        default-topic: sirh-notifications

# Configuration Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

# Nom du topic Kafka (configuration personnalisée)
notification:
  kafka:
    topic: sirh-notifications

