server:
  port: 8083

app.base-url: http://localhost:4200
file:
  upload-dir: ./uploads

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sirh_user_notif?serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    # Configurations de sécurité ici
  mail:
    host: vps104756.serveur-vps.net
    port: 587
    username: lamainapp@ngombe.org
    password: 4aeAgTJk!
    properties:
      mail:
        protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        notificationTopic-in-0: 
          destination: notifications
          group: user-notif-group
  
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-notification-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/resources/, classpath:/META-INF/resources/
  mvc:
    static-path-pattern: /uploads/**

jwt:
  secret: c980bef910d21eed63b5d4ea82c575ce82022fd139c3a183c2a9d163f3f73e5251f80762b718b4b293bcc37ea7163f7f1b3cc9f0101508f845fec8409e18fa3c
  expiration: 86400000
  refresh-token:
    expiration: 604800000

#logging:
#    level:
#      root: info
#      org:
#        springframework:
#          web: info

logging:
  level:
    org.springframework.security: DEBUG
    org:
      springframework:
        web: DEBUG

# app:
#   webhooks:
#     secret: 'c980bef910d21eed63b5d4ea82c575ce82022fd139c3a183c2a9d163f3f73e5251f80762b718b4b293bcc37ea7163f7f1b3cc9f0101508f845fec8409e18fa3c'
#     urls:
#       - 'http://localhost:8083/api/webhooks/notifications'
#       - 'https://api.lamainapp.com/webhooks/notifications'

notification:
  kafka:
    topic: sirh-notifications